### PR TITLE
Player movement script

### PR DESCRIPTION
**Pull request by Chetanpatil0501**
Player movement script added

### CODE REVIEW

**Review by rupamdebnath — APPROVED** [review]
Jump script looks good, velocity better option for player jump than AddForce

**Comment by Chetanpatil0501** [comment]
I added new script for smooth transition and also added cayote jump.

**Comment by rupamdebnath** [comment]
Hi Chetan,

Yes, that looks really good. Well done.

Kind regards,
Rupam

**Review by rupamdebnath — APPROVED** [review]
Looks good, well done.

**Pull request closed without merging**
